const GAMES_TO_WIN_SET = 6
const GAMES_IN_CLOSE_SET = 4
const GAMES_IN_ALT_SET = 3
const TIEBREAK_GAMES_WINNER = 7
const TIEBREAK_GAMES_LOSER = 5

const DEFAULT_RATING = 1500
const RATING_DELTA = 20
const ARCHIVED_RATING_DELTA = 40
const WINNER_RATING = DEFAULT_RATING + RATING_DELTA
const LOSER_RATING = DEFAULT_RATING - RATING_DELTA
const ARCHIVED_SINGLE_RATING = DEFAULT_RATING + ARCHIVED_RATING_DELTA

const STRAIGHT_SET_SCORE = [[GAMES_TO_WIN_SET, GAMES_IN_CLOSE_SET]]
const STRAIGHT_SET_SCORE_ALT = [[GAMES_TO_WIN_SET, GAMES_IN_ALT_SET]]
const SPLIT_SET_SCORE = [[GAMES_IN_CLOSE_SET, GAMES_TO_WIN_SET]]
const DRAW_SET_SCORE = [[GAMES_TO_WIN_SET, GAMES_TO_WIN_SET]]
const TIEBREAK_SET_SCORE = [[GAMES_IN_ALT_SET, 2, { tb: [TIEBREAK_GAMES_WINNER, TIEBREAK_GAMES_LOSER] }]]

export {
    ARCHIVED_SINGLE_RATING,
    DEFAULT_RATING,
    DRAW_SET_SCORE,
    LOSER_RATING,
    SPLIT_SET_SCORE,
    STRAIGHT_SET_SCORE,
    STRAIGHT_SET_SCORE_ALT,
    TIEBREAK_SET_SCORE,
    WINNER_RATING,
}
